### ISSUE TITLE
Slider image in truck modal needs bottom-padding

### ISSUE THREAD

**Issue by georgeweiler** [urban-pancake/hunger-stop#218]
Let me know if you have any questions.

**Comment by rcureton00** [comment]
I have questions.

**Comment by blakecontreras** [comment]
Don't worry, I'm all about paddling bottoms.

**Comment by blakecontreras** [comment]
@doug What is a slider image and where in yelpInfo.yelpInfo can I find it?

**Comment by rcureton00** [comment]
I imagine the former is a picture of a small hamburger. The latter an amalgam of JS.

**Comment by georgeweiler** [comment]
The slider image can be found my editing the truck-profile-slider-image-container-yelp-info-dot-truck css class. Check index.css. It's all in there.
